[View in Colaboratory](https://colab.research.google.com/github/wjmuse/aiacademy_course_study/blob/master/colab/ETF_model_LSTM.ipynb)

In [2]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Preconfiguring packages ...
Selecting previously unselected package cron.
(Reading database ... 18298 files and directories currently installed.)
Preparing to unpack .../00-cron_3.0pl1-128ubuntu5_amd64.deb ...
Unpacking cron (3.0pl1-128ubuntu5) ...
Selecting previously unselected package libapparmor1:amd64.
Preparing to unpack .../01-libapparmor1_2.11.0-2ubuntu17.1_amd64.deb ...
Unpacking libapparmor1:amd64 (2.11.0-2ubuntu17.1) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../02-libdbus-1-3_1.10.22-1ubuntu1_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Selecting previously unselected package dbus.
Preparing to unpack .../03-dbus_1.10.22-1ubuntu1_amd64.deb ...
Unpacking dbus (1.10.22-1ubuntu1) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../04-dirmngr_2.1.15-1ubuntu8_amd64.deb ...
Unpacking dirmngr (2.1.15-1ubuntu8) ...
Selecting previously unselected package distro-info-data.
Preparing to unpack .../0


Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up dirmngr (2.1.15-1ubuntu8) ...
Setting up cron (3.0pl1-128ubuntu5) ...
Adding group `crontab' (GID 102) ...
Done.
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: stop runlevel arguments (1) do not match cron Default-Stop values (none)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Setting up kmod (24-1ubuntu2) ...
Setting up libdbus-glib-1-2:amd64 (0.108-2) ...
Setting up python3-gi (3.24.1-2build1) ...
Setting up module-init-tools (24-1ubuntu2) ...
Setting up python3-software-properties (0.96.24.17) ...
Setting up dbus (1.10.22-1ubuntu1) ...
Setting up python-apt (1.4.0~beta3build2) ...
Setting up python3-dbus (1.2.4-1buil

In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [4]:
!ls drive/aia-colab/ | head -5

colab_mnist_hello_world.ipynb
ETF_model_LSTM.ipynb
examples
twetf


In [0]:
#@title
!gsutil -m cp -r gs://pixnet-gt-sharedata/wayne-test/twetf ./drive/aia-colab/ 
#!gsutil -m cp -r gs://pixnet-gt-sharedata/wayne-test/stock-groupbycode ./drive/aia-colab/ 

Copying gs://pixnet-gt-sharedata/wayne-test/twetf/.gitignore...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/README.md...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/README.md...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/README.txt...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/fake_answer.tsv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/raw/tetfp.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/answer_example.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/read_df_demo.py...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/submit_example.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/raw/tsharep.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/tasharep.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/taetfp.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/data/tetfp.csv...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/README.md...
Copying

Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/__pycache__/__init__.cpython-36.pyc...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/__pycache__/ml.cpython-36.pyc...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/__pycache__/tech.cpython-36.pyc...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/__pycache__/utils.cpython-36.pyc...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/ml.py...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/tech.py...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/etf_tools/utils.py...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/ETF_CandleStick.ipynb...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/ETF_KD_RSV180424.ipynb...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/ETF_MACD.ipynb...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/ETF_RSI.ipynb...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/ETF_VR_OBV.ipynb...
Copying gs://pixnet

Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/ETF_model_LSTM.ipynb...
Copying gs://pixnet-gt-sharedata/wayne-test/twetf/larry/LSTM_20_5_D_180506.save...


In [0]:
!cp twetf/larry/prepare_data.py .

In [0]:
import numpy as np
import pandas as pd
from collections import OrderedDict
from time import time

from prepare_data import get_sliding_window

In [10]:
 # read in csv, change column names
etf = pd.read_csv('twetf/data/tetfp.csv')
col_dtypes = OrderedDict(code=str, date=str, name=str, open=float, high=float, low=float, close=float, volume=int)

etf.columns=col_dtypes.keys()

etf.head()

high      code    name  volume    low   date  close   open
0    50  20130102  元大台灣50   54.00  54.65  53.90  54.40  16487
1    50  20130103  元大台灣50   54.90  55.05  54.65  54.85  29020
2    50  20130104  元大台灣50   54.85  54.85  54.40  54.50   9837
3    50  20130107  元大台灣50   54.55  54.55  53.90  54.25   8910
4    50  20130108  元大台灣50   54.00  54.20  53.65  53.90  12507

In [11]:
etf= etf[:1286] # select 台灣50 
etf.tail()

high      code    name  volume    low   date  close  open
1281    50  20180327  元大台灣50   83.00  83.40  82.95  83.40  3277
1282    50  20180328  元大台灣50   82.90  82.90  82.20  82.25  4161
1283    50  20180329  元大台灣50   82.25  82.35  81.80  82.10  4099
1284    50  20180330  元大台灣50   82.65  83.05  82.65  82.85  4994
1285    50  20180331  元大台灣50   82.85  83.05  82.75  82.95   878

In [12]:
etf['target'] = etf.close.diff().fillna(0)
etf['target_signal'] = np.where(etf.close.diff().fillna(0) >=0,1,-1) 
etf

high      code    name  volume    low   date  close   open  target  \
0       50  20130102  元大台灣50   54.00  54.65  53.90  54.40  16487    0.00   
1       50  20130103  元大台灣50   54.90  55.05  54.65  54.85  29020    0.45   
2       50  20130104  元大台灣50   54.85  54.85  54.40  54.50   9837   -0.35   
3       50  20130107  元大台灣50   54.55  54.55  53.90  54.25   8910   -0.25   
4       50  20130108  元大台灣50   54.00  54.20  53.65  53.90  12507   -0.35   
5       50  20130109  元大台灣50   53.75  54.30  53.75  54.10   7529    0.20   
6       50  20130110  元大台灣50   54.30  54.65  54.15  54.50  13953    0.40   
7       50  20130111  元大台灣50   54.70  54.80  54.35  54.45  11837   -0.05   
8       50  20130114  元大台灣50   54.00  54.50  53.80  54.50   7282    0.05   
9       50  20130115  元大台灣50   54.20  54.45  53.90  54.00   6609   -0.50   
10      50  20130116  元大台灣50   54.05  54.05  53.70  53.70   8142   -0.30   
11      50  20130117  元大台灣50   53.90  54.20  53.20  53.30  10084   -0.40   
12      50  20130118  元大台灣50   53.95  53.95  53.70  53.95   5410    0.65   
13      50  20130121  元大台灣50   53.95  54.05  53.55  53.90   4525   -0.05   
14      50  20130122  元大台灣50   54.30  54.30  53.70  54.05  10501    0.15   
15      50  20130123  元大台灣50   54.20  54.30  53.90  54.00   7266   -0.05   
16      50  20130124  元大台灣50   53.75  53.90  53.25  53.70  11334   -0.30   
17      50  20130125  元大台灣50   53.65  53.70  53.20  53.50   8521   -0.20   
18      50  20130128  元大台灣50   53.70  53.95  53.65  53.75   8708    0.25   
19      50  20130129  元大台灣50   53.95  54.50  53.95  54.50  21973    0.75   
20      50  20130130  元大台灣50   54.50  54.75  54.45  54.60  21672    0.10   
21      50  20130131  元大台灣50   54.50  54.60  54.30  54.60  12643    0.00   
22      50  20130201  元大台灣50   54.70  54.85  54.60  54.80  15057    0.20   
23      50  20130204  元大台灣50   54.85  55.40  54.85  55.20  30980    0.40   
24      50  20130205  元大台灣50   54.90  55.10  54.90  55.00  15988   -0.20   
25      50  20130206  元大台灣50   55.20  55.50  55.20  55.40  29434    0.40   
26      50  20130218  元大台灣50   55.50  55.90  55.45  55.60  29739    0.20   
27      50  20130219  元大台灣50   55.60  55.75  55.55  55.65  16817    0.05   
28      50  20130220  元大台灣50   55.90  56.20  55.90  56.10  21814    0.45   
29      50  20130221  元大台灣50   55.90  56.05  55.70  55.70   9951   -0.40   
...    ...       ...     ...     ...    ...    ...    ...    ...     ...   
1256    50  20180209  元大台灣50   78.60  79.20  78.00  79.05  16211   -1.55   
1257    50  20180212  元大台灣50   79.55  79.90  79.40  79.70   8443    0.65   
1258    50  20180221  元大台灣50   81.40  81.70  81.10  81.50  11646    1.80   
1259    50  20180222  元大台灣50   81.50  81.50  80.75  81.00   3749   -0.50   
1260    50  20180223  元大台灣50   81.40  82.10  81.40  82.00   3779    1.00   
1261    50  20180226  元大台灣50   82.55  82.80  82.35  82.40   3289    0.40   
1262    50  20180227  元大台灣50   83.10  83.20  82.35  82.35   7663   -0.05   
1263    50  20180301  元大台灣50   81.55  81.95  81.15  81.75   4344   -0.60   
1264    50  20180302  元大台灣50   80.85  81.20  80.45  81.15   6262   -0.60   
1265    50  20180305  元大台灣50   81.10  81.50  80.65  80.75   3723   -0.40   
1266    50  20180306  元大台灣50   81.65  82.15  81.60  82.15   5732    1.40   
1267    50  20180307  元大台灣50   81.75  82.45  81.70  81.80   2619   -0.35   
1268    50  20180308  元大台灣50   82.15  82.80  82.15  82.75   3232    0.95   
1269    50  20180309  元大台灣50   82.90  83.00  82.70  82.85   2832    0.10   
1270    50  20180312  元大台灣50   83.60  84.25  83.55  84.15   8752    1.30   
1271    50  20180313  元大台灣50   84.35  84.95  84.30  84.95   9837    0.80   
1272    50  20180314  元大台灣50   84.35  84.45  84.00  84.30   3415   -0.65   
1273    50  20180315  元大台灣50   84.00  84.30  83.90  84.25   3506   -0.05   
1274    50  20180316  元大台灣50   84.00  84.20  83.10  83.90   5510   -0.35   
1275    50  20180319  元大台灣50   83.65  84.10  83.45  83.85   2035   -0.05   
1276    50  20180320  元大台灣50   83.20  83.80  83.20  83

In [13]:
from sklearn import preprocessing

def normalize(df):
    newdf= df.copy()
    min_max_scaler = preprocessing.MinMaxScaler()

    newdf['open'] = min_max_scaler.fit_transform(df.open.values.reshape(-1,1))
    newdf['low'] = min_max_scaler.fit_transform(df.low.values.reshape(-1,1))
    newdf['high'] = min_max_scaler.fit_transform(df.high.values.reshape(-1,1))
    newdf['volume'] = min_max_scaler.fit_transform(df.volume.values.reshape(-1,1))
    newdf['close'] = min_max_scaler.fit_transform(df.close.values.reshape(-1,1))
    newdf['target'] = min_max_scaler.fit_transform(df.target.values.reshape(-1,1))
    newdf['target_signal'] = min_max_scaler.fit_transform(df.target_signal.values.reshape(-1,1))
    #newdf['target_signal'] = df.target_signal
    return newdf
new_etf = normalize(etf)

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
new_etf

high      code    name    volume       low   date     close      open  \
0      0.0  20130102  元大台灣50  0.020144  0.032951  53.90  0.039660  0.259106   
1      0.0  20130103  元大台灣50  0.046043  0.044413  54.65  0.052408  0.466236   
2      0.0  20130104  元大台灣50  0.044604  0.038682  54.40  0.042493  0.149203   
3      0.0  20130107  元大台灣50  0.035971  0.030086  53.90  0.035411  0.133883   
4      0.0  20130108  元大台灣50  0.020144  0.020057  53.65  0.025496  0.193330   
5      0.0  20130109  元大台灣50  0.012950  0.022923  53.75  0.031161  0.111060   
6      0.0  20130110  元大台灣50  0.028777  0.032951  54.15  0.042493  0.217227   
7      0.0  20130111  元大台灣50  0.040288  0.037249  54.35  0.041076  0.182257   
8      0.0  20130114  元大台灣50  0.020144  0.028653  53.80  0.042493  0.106978   
9      0.0  20130115  元大台灣50  0.025899  0.027221  53.90  0.028329  0.095855   
10     0.0  20130116  元大台灣50  0.021583  0.015759  53.70  0.019830  0.121191   
11     0.0  20130117  元大台灣50  0.017266  0.020057  53.20  0.008499  0.153286   
12     0.0  20130118  元大台灣50  0.018705  0.012894  53.70  0.026912  0.076040   
13     0.0  20130121  元大台灣50  0.018705  0.015759  53.55  0.025496  0.061413   
14     0.0  20130122  元大台灣50  0.028777  0.022923  53.70  0.029745  0.160177   
15     0.0  20130123  元大台灣50  0.025899  0.022923  53.90  0.028329  0.106713   
16     0.0  20130124  元大台灣50  0.012950  0.011461  53.25  0.019830  0.173944   
17     0.0  20130125  元大台灣50  0.010072  0.005731  53.20  0.014164  0.127454   
18     0.0  20130128  元大台灣50  0.011511  0.012894  53.65  0.021246  0.130545   
19     0.0  20130129  元大台灣50  0.018705  0.028653  53.95  0.042493  0.349772   
20     0.0  20130130  元大台灣50  0.034532  0.035817  54.45  0.045326  0.344797   
21     0.0  20130131  元大台灣50  0.034532  0.031519  54.30  0.045326  0.195577   
22     0.0  20130201  元大台灣50  0.040288  0.038682  54.60  0.050992  0.235473   
23     0.0  20130204  元大台灣50  0.044604  0.054441  54.85  0.062323  0.498628   
24     0.0  20130205  元大台灣50  0.046043  0.045845  54.90  0.056657  0.250859   
25     0.0  20130206  元大台灣50  0.054676  0.057307  55.20  0.067989  0.473078   
26     0.0  20130218  元大台灣50  0.063309  0.068768  55.45  0.073654  0.478119   
27     0.0  20130219  元大台灣50  0.066187  0.064470  55.55  0.075071  0.264560   
28     0.0  20130220  元大台灣50  0.074820  0.077364  55.90  0.087819  0.347144   
29     0.0  20130221  元大台灣50  0.074820  0.073066  55.70  0.076487  0.151087   
...    ...       ...     ...       ...       ...    ...       ...       ...   
1256   0.0  20180209  元大台灣50  0.728058  0.736390  78.00  0.737960  0.254545   
1257   0.0  20180212  元大台灣50  0.755396  0.756447  79.40  0.756374  0.126165   
1258   0.0  20180221  元大台灣50  0.808633  0.808023  81.10  0.807365  0.179100   
1259   0.0  20180222  元大台灣50  0.811511  0.802292  80.75  0.793201  0.048589   
1260   0.0  20180223  元大台灣50  0.808633  0.819484  81.40  0.821530  0.049084   
1261   0.0  20180226  元大台灣50  0.841727  0.839542  82.35  0.832861  0.040986   
1262   0.0  20180227  元大台灣50  0.857554  0.851003  82.35  0.831445  0.113274   
1263   0.0  20180301  元大台灣50  0.812950  0.815186  81.15  0.814448  0.058422   
1264   0.0  20180302  元大台灣50  0.792806  0.793696  80.45  0.797450  0.090120   
1265   0.0  20180305  元大台灣50  0.800000  0.802292  80.65  0.786119  0.048159   
1266   0.0  20180306  元大台灣50  0.815827  0.820917  81.60  0.825779  0.081361   
1267   0.0  20180307  元大台灣50  0.818705  0.829513  81.70  0.815864  0.029913   
1268   0.0  20180308  元大台灣50  0.830216  0.839542  82.15  0.842776  0.040044   
1269   0.0  20180309  元大台灣50  0.851799  0.845272  82.70  0.845609  0.033434   
1270   0.0  20180312  元大台灣50  0.871942  0.881089  83.55  0.882436  0.131272   
1271   0.0  20180313  元大台灣50  0.893525  0.901146  84.30  0.905099  0.149203   
1272   0.0  20180314  元大台灣50  0.893525  0.886819  84.00  0.886686  0.043069   
1273   0.0  20180315  元大台灣50  0.883453  0.882521  83.90  0.885269  0.044573   
1274   0.0  20180316  元大台灣50  0.883453  0.879656  83.10 

In [15]:
new_etf.columns 

Index([u'high', u'code', u'name', u'volume', u'low', u'date', u'close',
       u'open', u'target', u'target_signal'],
      dtype='object')

In [0]:
feature_cols = ['open', 'high', 'low', 'close', 'volume']

In [0]:
def prepare_data(feature_df, feature_cols, target_df, input_days=20,output_days=5):
    
    
    '''
    feature_df: the compelet feature set 
    feature_cols : subset of features,   if needs to select subset from the complete features set
    
    
    '''
    reduce_feature_df = feature_df[feature_cols].iloc[:len(feature_df)-output_days] 
    print ('len_X',reduce_feature_df.shape)
    print (reduce_feature_df)
    
    target_y  = target_df.iloc[input_days:]
    
    print ('len_y',target_y.shape)
    print (target_y)
    
    data_X =get_sliding_window(reduce_feature_df, n_days=input_days)
    data_y = get_sliding_window(target_y, n_days=output_days)
    
    data_dict = {'training_X': data_X,
                'training_y': data_y}
    
    return data_dict
    

In [19]:
data = prepare_data(new_etf, feature_cols, new_etf[['target','target_signal']])

('len_X', (1281, 5))
          open  high       low     close    volume
0     0.259106   0.0  0.032951  0.039660  0.020144
1     0.466236   0.0  0.044413  0.052408  0.046043
2     0.149203   0.0  0.038682  0.042493  0.044604
3     0.133883   0.0  0.030086  0.035411  0.035971
4     0.193330   0.0  0.020057  0.025496  0.020144
5     0.111060   0.0  0.022923  0.031161  0.012950
6     0.217227   0.0  0.032951  0.042493  0.028777
7     0.182257   0.0  0.037249  0.041076  0.040288
8     0.106978   0.0  0.028653  0.042493  0.020144
9     0.095855   0.0  0.027221  0.028329  0.025899
10    0.121191   0.0  0.015759  0.019830  0.021583
11    0.153286   0.0  0.020057  0.008499  0.017266
12    0.076040   0.0  0.012894  0.026912  0.018705
13    0.061413   0.0  0.015759  0.025496  0.018705
14    0.160177   0.0  0.022923  0.029745  0.028777
15    0.106713   0.0  0.022923  0.028329  0.025899
16    0.173944   0.0  0.011461  0.019830  0.012950
17    0.127454   0.0  0.005731  0.014164  0.010072
18    0.13

In [20]:
data['training_X'].shape

(1262, 20, 5)

In [22]:
data['training_y'].shape

(1262, 5, 2)

In [23]:
from sklearn.model_selection import train_test_split 

X = data['training_X']
Y = data['training_y'][:,:,1]  # only use target signal 
Y = Y[:,:,np.newaxis] # expand one more axis to align with NN outoput 
print (X.shape)
print (Y.shape)


#K_binary = keras.utils.to_categorical(K_label,2)
X_train, X_test, Y_train,Y_test = train_test_split (X,Y, test_size=0.2,shuffle=True)

#Y_train =  Y_train[:,:,np.newaxis]
#Y_test =  Y_test[:,:,np.newaxis]
#Y_train = np.array(Y_train)
print (X_train.shape)
print (Y_train.shape)
print (Y_train[:10])

(1262, 20, 5)
(1262, 5, 1)
(1009, 20, 5)
(1009, 5, 1)
[[[0.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [0.]
  [1.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[0.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[0.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [0.]
  [0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[0.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [1.]
  [1.]
  [1.]]]


In [0]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.recurrent import LSTM
import keras


from keras.optimizers import Adam,SGD

from keras.layers import Input, Embedding, LSTM, Dense
from keras.models import Model
from keras.optimizers import Adam 
from keras.losses import binary_crossentropy
from keras.layers import Dropout
from keras.utils import to_categorical
from keras.layers import Reshape

from keras.layers import Lambda

In [26]:
#def build_model(input_length, input_dim):
input_length, input_dim = 20,5

d = 0.2

main_input = Input(shape=(input_length,input_dim),  name='main_input')
lstm_1 = LSTM(64, return_sequences=True, name='lastm_1')(main_input)
lstm_1 = Dropout(d)(lstm_1)
lstm_2 = LSTM(128, return_sequences=True, name='lastm_2')(lstm_1)
lstm_2 = Dropout(d)(lstm_2)
#lstm_3 = LSTM(128, return_sequences=False, name='lastm_3')(main_input)


lstm_3 = LSTM(128, return_sequences=False, name='lastm_3')(lstm_2)
lstm_3 = Dropout(d)(lstm_3)
logit = Dense(128, activation='relu', name='logit')(lstm_3)
logit = Dropout(d)(logit)

logit = Dense(64, activation='relu', name='logit_2')(logit)
logit = Dropout(d)(logit)


output = Dense(5, activation='sigmoid', name='output')(logit)
output = Dropout(d)(output)

# Using Lambda function to get multiple output 
# Need reshape to allign with Shape of Train_Y

output_0 = Lambda(lambda x: x[:,0])(output)
output_0 = Reshape((-1,))(output_0) 
output_1 = Lambda(lambda x: x[:,1])(output)
output_1 = Reshape((-1,))(output_1)
output_2 = Lambda(lambda x: x[:,2])(output)
output_2 = Reshape((-1,))(output_2)
output_3 = Lambda(lambda x: x[:,3])(output)
output_3 = Reshape((-1,))(output_3)
output_4 = Lambda(lambda x: x[:,4])(output)
output_4 = Reshape((-1,))(output_4)


#loss_type = 'mse'
loss_type = 'binary_crossentropy'
combine_loss = [loss_type]*5


model = Model(inputs=main_input, outputs=[output_0,output_1,output_2, output_3, output_4])
adam_op = Adam(lr=0.001)
model.compile(optimizer=adam_op, loss=combine_loss, metrics=['accuracy'])

print (model.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main_input (InputLayer)         (None, 20, 5)        0                                            
__________________________________________________________________________________________________
lastm_1 (LSTM)                  (None, 20, 64)       17920       main_input[0][0]                 
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 20, 64)       0           lastm_1[0][0]                    
__________________________________________________________________________________________________
lastm_2 (LSTM)                  (None, 20, 128)      98816       dropout_1[0][0]                  
__________________________________________________________________________________________________
dropout_2 

In [27]:
print (Y_train.shape)

Y = [Y_train[:,i,:] for i in range(5)]  # simplify expression 
model.fit (X_train, Y, batch_size=64, epochs=500, validation_split=0.2,verbose=2)

(1009, 5, 1)
Train on 807 samples, validate on 202 samples
Epoch 1/500
 - 3s - loss: 12.1013 - reshape_1_loss: 2.1959 - reshape_2_loss: 2.4263 - reshape_3_loss: 2.7122 - reshape_4_loss: 2.3628 - reshape_5_loss: 2.4040 - reshape_1_acc: 0.5304 - reshape_2_acc: 0.5304 - reshape_3_acc: 0.5143 - reshape_4_acc: 0.5551 - reshape_5_acc: 0.5341 - val_loss: 3.5141 - val_reshape_1_loss: 0.7075 - val_reshape_2_loss: 0.7073 - val_reshape_3_loss: 0.6960 - val_reshape_4_loss: 0.6934 - val_reshape_5_loss: 0.7099 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 2/500
 - 2s - loss: 11.6993 - reshape_1_loss: 2.5674 - reshape_2_loss: 2.1569 - reshape_3_loss: 2.3848 - reshape_4_loss: 2.2686 - reshape_5_loss: 2.3217 - reshape_1_acc: 0.5093 - reshape_2_acc: 0.5415 - reshape_3_acc: 0.5440 - reshape_4_acc: 0.5551 - reshape_5_acc: 0.5316 - val_loss: 3.5431 - val_reshape_1_loss: 0.7129 - val_reshape_2_loss: 0.7182 - 

 - 2s - loss: 12.1333 - reshape_1_loss: 2.4777 - reshape_2_loss: 2.4008 - reshape_3_loss: 2.4553 - reshape_4_loss: 2.3601 - reshape_5_loss: 2.4393 - reshape_1_acc: 0.5304 - reshape_2_acc: 0.5366 - reshape_3_acc: 0.5229 - reshape_4_acc: 0.5489 - reshape_5_acc: 0.5204 - val_loss: 3.5508 - val_reshape_1_loss: 0.7223 - val_reshape_2_loss: 0.7139 - val_reshape_3_loss: 0.6982 - val_reshape_4_loss: 0.6972 - val_reshape_5_loss: 0.7192 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 14/500
 - 2s - loss: 12.3962 - reshape_1_loss: 2.5035 - reshape_2_loss: 2.7230 - reshape_3_loss: 2.3898 - reshape_4_loss: 2.3381 - reshape_5_loss: 2.4418 - reshape_1_acc: 0.5254 - reshape_2_acc: 0.5254 - reshape_3_acc: 0.5378 - reshape_4_acc: 0.5341 - reshape_5_acc: 0.5254 - val_loss: 3.5464 - val_reshape_1_loss: 0.7208 - val_reshape_2_loss: 0.7163 - val_reshape_3_loss: 0.6981 - val_reshape_4_loss: 0.6970 - val_reshape_

Epoch 26/500
 - 2s - loss: 11.8294 - reshape_1_loss: 2.6466 - reshape_2_loss: 2.3467 - reshape_3_loss: 2.4396 - reshape_4_loss: 2.2444 - reshape_5_loss: 2.1521 - reshape_1_acc: 0.5006 - reshape_2_acc: 0.5341 - reshape_3_acc: 0.5428 - reshape_4_acc: 0.5589 - reshape_5_acc: 0.5477 - val_loss: 3.5361 - val_reshape_1_loss: 0.7190 - val_reshape_2_loss: 0.7108 - val_reshape_3_loss: 0.6979 - val_reshape_4_loss: 0.6943 - val_reshape_5_loss: 0.7141 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 27/500
 - 2s - loss: 12.0929 - reshape_1_loss: 2.1561 - reshape_2_loss: 2.5978 - reshape_3_loss: 2.6458 - reshape_4_loss: 2.4508 - reshape_5_loss: 2.2424 - reshape_1_acc: 0.5440 - reshape_2_acc: 0.5229 - reshape_3_acc: 0.5093 - reshape_4_acc: 0.5304 - reshape_5_acc: 0.5167 - val_loss: 3.5587 - val_reshape_1_loss: 0.7263 - val_reshape_2_loss: 0.7147 - val_reshape_3_loss: 0.6998 - val_reshape_4_loss: 0.6959 -

Epoch 39/500
 - 2s - loss: 11.8522 - reshape_1_loss: 2.5951 - reshape_2_loss: 2.1213 - reshape_3_loss: 2.3959 - reshape_4_loss: 2.3783 - reshape_5_loss: 2.3616 - reshape_1_acc: 0.5167 - reshape_2_acc: 0.5651 - reshape_3_acc: 0.5502 - reshape_4_acc: 0.5502 - reshape_5_acc: 0.5118 - val_loss: 3.5454 - val_reshape_1_loss: 0.7248 - val_reshape_2_loss: 0.7097 - val_reshape_3_loss: 0.6970 - val_reshape_4_loss: 0.6962 - val_reshape_5_loss: 0.7177 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4356 - val_reshape_3_acc: 0.4901 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4208
Epoch 40/500
 - 2s - loss: 12.2201 - reshape_1_loss: 2.5855 - reshape_2_loss: 2.3290 - reshape_3_loss: 2.3548 - reshape_4_loss: 2.4611 - reshape_5_loss: 2.4897 - reshape_1_acc: 0.5056 - reshape_2_acc: 0.5366 - reshape_3_acc: 0.5539 - reshape_4_acc: 0.5390 - reshape_5_acc: 0.5118 - val_loss: 3.5494 - val_reshape_1_loss: 0.7352 - val_reshape_2_loss: 0.7035 - val_reshape_3_loss: 0.6986 - val_reshape_4_loss: 0.6970 -

Epoch 52/500
 - 2s - loss: 11.3845 - reshape_1_loss: 1.9037 - reshape_2_loss: 2.4803 - reshape_3_loss: 2.5735 - reshape_4_loss: 2.2393 - reshape_5_loss: 2.1876 - reshape_1_acc: 0.5700 - reshape_2_acc: 0.5366 - reshape_3_acc: 0.5353 - reshape_4_acc: 0.5403 - reshape_5_acc: 0.5366 - val_loss: 3.5368 - val_reshape_1_loss: 0.7211 - val_reshape_2_loss: 0.7093 - val_reshape_3_loss: 0.7004 - val_reshape_4_loss: 0.6971 - val_reshape_5_loss: 0.7089 - val_reshape_1_acc: 0.4257 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5149 - val_reshape_5_acc: 0.4505
Epoch 53/500
 - 2s - loss: 12.2096 - reshape_1_loss: 2.5810 - reshape_2_loss: 2.3431 - reshape_3_loss: 2.5547 - reshape_4_loss: 2.2961 - reshape_5_loss: 2.4347 - reshape_1_acc: 0.5068 - reshape_2_acc: 0.5403 - reshape_3_acc: 0.5093 - reshape_4_acc: 0.5613 - reshape_5_acc: 0.5304 - val_loss: 3.5586 - val_reshape_1_loss: 0.7235 - val_reshape_2_loss: 0.7147 - val_reshape_3_loss: 0.7037 - val_reshape_4_loss: 0.6992 -

Epoch 65/500
 - 2s - loss: 11.9077 - reshape_1_loss: 2.4834 - reshape_2_loss: 2.4383 - reshape_3_loss: 2.2872 - reshape_4_loss: 2.4342 - reshape_5_loss: 2.2646 - reshape_1_acc: 0.5316 - reshape_2_acc: 0.5316 - reshape_3_acc: 0.5452 - reshape_4_acc: 0.5403 - reshape_5_acc: 0.5366 - val_loss: 3.5479 - val_reshape_1_loss: 0.7330 - val_reshape_2_loss: 0.7073 - val_reshape_3_loss: 0.7008 - val_reshape_4_loss: 0.6956 - val_reshape_5_loss: 0.7112 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4505 - val_reshape_3_acc: 0.5149 - val_reshape_4_acc: 0.5099 - val_reshape_5_acc: 0.4554
Epoch 66/500
 - 2s - loss: 12.0818 - reshape_1_loss: 2.3510 - reshape_2_loss: 2.5491 - reshape_3_loss: 2.4714 - reshape_4_loss: 2.5001 - reshape_5_loss: 2.2101 - reshape_1_acc: 0.5564 - reshape_2_acc: 0.5266 - reshape_3_acc: 0.5489 - reshape_4_acc: 0.5378 - reshape_5_acc: 0.5428 - val_loss: 3.5750 - val_reshape_1_loss: 0.7386 - val_reshape_2_loss: 0.7152 - val_reshape_3_loss: 0.7053 - val_reshape_4_loss: 0.6986 -

Epoch 78/500
 - 2s - loss: 11.7294 - reshape_1_loss: 2.3496 - reshape_2_loss: 2.5052 - reshape_3_loss: 2.1549 - reshape_4_loss: 2.4574 - reshape_5_loss: 2.2624 - reshape_1_acc: 0.5638 - reshape_2_acc: 0.5415 - reshape_3_acc: 0.5812 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5440 - val_loss: 3.5528 - val_reshape_1_loss: 0.7194 - val_reshape_2_loss: 0.7182 - val_reshape_3_loss: 0.7046 - val_reshape_4_loss: 0.6927 - val_reshape_5_loss: 0.7179 - val_reshape_1_acc: 0.4208 - val_reshape_2_acc: 0.4257 - val_reshape_3_acc: 0.5099 - val_reshape_4_acc: 0.4851 - val_reshape_5_acc: 0.4406
Epoch 79/500
 - 2s - loss: 11.9270 - reshape_1_loss: 2.2957 - reshape_2_loss: 2.4769 - reshape_3_loss: 2.2623 - reshape_4_loss: 2.3733 - reshape_5_loss: 2.5188 - reshape_1_acc: 0.5638 - reshape_2_acc: 0.5341 - reshape_3_acc: 0.5465 - reshape_4_acc: 0.5353 - reshape_5_acc: 0.5353 - val_loss: 3.5864 - val_reshape_1_loss: 0.7272 - val_reshape_2_loss: 0.7323 - val_reshape_3_loss: 0.7058 - val_reshape_4_loss: 0.6970 -

Epoch 91/500
 - 2s - loss: 11.6288 - reshape_1_loss: 2.3132 - reshape_2_loss: 2.5980 - reshape_3_loss: 2.4329 - reshape_4_loss: 2.1537 - reshape_5_loss: 2.1310 - reshape_1_acc: 0.5378 - reshape_2_acc: 0.5254 - reshape_3_acc: 0.5378 - reshape_4_acc: 0.5601 - reshape_5_acc: 0.5527 - val_loss: 3.5462 - val_reshape_1_loss: 0.7287 - val_reshape_2_loss: 0.7079 - val_reshape_3_loss: 0.6936 - val_reshape_4_loss: 0.6953 - val_reshape_5_loss: 0.7207 - val_reshape_1_acc: 0.4208 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.5248 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4307
Epoch 92/500
 - 2s - loss: 11.7178 - reshape_1_loss: 2.2986 - reshape_2_loss: 2.3342 - reshape_3_loss: 2.2176 - reshape_4_loss: 2.6051 - reshape_5_loss: 2.2622 - reshape_1_acc: 0.5713 - reshape_2_acc: 0.5514 - reshape_3_acc: 0.5539 - reshape_4_acc: 0.5489 - reshape_5_acc: 0.5576 - val_loss: 3.5493 - val_reshape_1_loss: 0.7259 - val_reshape_2_loss: 0.7103 - val_reshape_3_loss: 0.6981 - val_reshape_4_loss: 0.6973 -

Epoch 104/500
 - 2s - loss: 11.6552 - reshape_1_loss: 2.2993 - reshape_2_loss: 2.4188 - reshape_3_loss: 2.2017 - reshape_4_loss: 2.2729 - reshape_5_loss: 2.4625 - reshape_1_acc: 0.5613 - reshape_2_acc: 0.5428 - reshape_3_acc: 0.5750 - reshape_4_acc: 0.5514 - reshape_5_acc: 0.5341 - val_loss: 3.5608 - val_reshape_1_loss: 0.7308 - val_reshape_2_loss: 0.7155 - val_reshape_3_loss: 0.7004 - val_reshape_4_loss: 0.6973 - val_reshape_5_loss: 0.7168 - val_reshape_1_acc: 0.4208 - val_reshape_2_acc: 0.4703 - val_reshape_3_acc: 0.5149 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.4802
Epoch 105/500
 - 2s - loss: 12.0223 - reshape_1_loss: 2.3535 - reshape_2_loss: 2.4795 - reshape_3_loss: 2.3543 - reshape_4_loss: 2.5809 - reshape_5_loss: 2.2542 - reshape_1_acc: 0.5440 - reshape_2_acc: 0.5527 - reshape_3_acc: 0.5502 - reshape_4_acc: 0.5489 - reshape_5_acc: 0.5601 - val_loss: 3.5648 - val_reshape_1_loss: 0.7297 - val_reshape_2_loss: 0.7152 - val_reshape_3_loss: 0.7006 - val_reshape_4_loss: 0.6998

Epoch 117/500
 - 2s - loss: 11.8342 - reshape_1_loss: 2.3844 - reshape_2_loss: 2.4332 - reshape_3_loss: 2.2847 - reshape_4_loss: 2.2861 - reshape_5_loss: 2.4457 - reshape_1_acc: 0.5626 - reshape_2_acc: 0.5390 - reshape_3_acc: 0.5651 - reshape_4_acc: 0.5675 - reshape_5_acc: 0.5217 - val_loss: 3.5432 - val_reshape_1_loss: 0.7268 - val_reshape_2_loss: 0.7123 - val_reshape_3_loss: 0.7005 - val_reshape_4_loss: 0.6929 - val_reshape_5_loss: 0.7108 - val_reshape_1_acc: 0.4406 - val_reshape_2_acc: 0.4653 - val_reshape_3_acc: 0.5248 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.5050
Epoch 118/500
 - 2s - loss: 12.0531 - reshape_1_loss: 2.3618 - reshape_2_loss: 2.4251 - reshape_3_loss: 2.5981 - reshape_4_loss: 2.4839 - reshape_5_loss: 2.1842 - reshape_1_acc: 0.5576 - reshape_2_acc: 0.5514 - reshape_3_acc: 0.5638 - reshape_4_acc: 0.5638 - reshape_5_acc: 0.5688 - val_loss: 3.5650 - val_reshape_1_loss: 0.7304 - val_reshape_2_loss: 0.7253 - val_reshape_3_loss: 0.6994 - val_reshape_4_loss: 0.6925

Epoch 130/500
 - 2s - loss: 11.2945 - reshape_1_loss: 2.3672 - reshape_2_loss: 2.2392 - reshape_3_loss: 2.3208 - reshape_4_loss: 2.2039 - reshape_5_loss: 2.1634 - reshape_1_acc: 0.5601 - reshape_2_acc: 0.5750 - reshape_3_acc: 0.5675 - reshape_4_acc: 0.5812 - reshape_5_acc: 0.5428 - val_loss: 3.5911 - val_reshape_1_loss: 0.7467 - val_reshape_2_loss: 0.7169 - val_reshape_3_loss: 0.6932 - val_reshape_4_loss: 0.7031 - val_reshape_5_loss: 0.7312 - val_reshape_1_acc: 0.4307 - val_reshape_2_acc: 0.4554 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.4455
Epoch 131/500
 - 2s - loss: 11.6277 - reshape_1_loss: 2.0426 - reshape_2_loss: 2.4093 - reshape_3_loss: 2.2471 - reshape_4_loss: 2.5733 - reshape_5_loss: 2.3554 - reshape_1_acc: 0.6010 - reshape_2_acc: 0.5390 - reshape_3_acc: 0.5824 - reshape_4_acc: 0.5613 - reshape_5_acc: 0.5750 - val_loss: 3.5856 - val_reshape_1_loss: 0.7342 - val_reshape_2_loss: 0.7274 - val_reshape_3_loss: 0.6970 - val_reshape_4_loss: 0.7024

Epoch 143/500
 - 2s - loss: 11.5536 - reshape_1_loss: 2.3705 - reshape_2_loss: 2.3068 - reshape_3_loss: 2.5757 - reshape_4_loss: 2.2689 - reshape_5_loss: 2.0317 - reshape_1_acc: 0.5737 - reshape_2_acc: 0.5750 - reshape_3_acc: 0.5601 - reshape_4_acc: 0.5663 - reshape_5_acc: 0.5527 - val_loss: 3.5507 - val_reshape_1_loss: 0.7230 - val_reshape_2_loss: 0.7137 - val_reshape_3_loss: 0.6897 - val_reshape_4_loss: 0.6991 - val_reshape_5_loss: 0.7252 - val_reshape_1_acc: 0.4158 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.5347 - val_reshape_4_acc: 0.5099 - val_reshape_5_acc: 0.4307
Epoch 144/500
 - 2s - loss: 11.7287 - reshape_1_loss: 2.1802 - reshape_2_loss: 2.3138 - reshape_3_loss: 2.3128 - reshape_4_loss: 2.3127 - reshape_5_loss: 2.6093 - reshape_1_acc: 0.5576 - reshape_2_acc: 0.5440 - reshape_3_acc: 0.5601 - reshape_4_acc: 0.5601 - reshape_5_acc: 0.5328 - val_loss: 3.5959 - val_reshape_1_loss: 0.7422 - val_reshape_2_loss: 0.7200 - val_reshape_3_loss: 0.7045 - val_reshape_4_loss: 0.7059

Epoch 156/500
 - 2s - loss: 11.9240 - reshape_1_loss: 2.3463 - reshape_2_loss: 2.4281 - reshape_3_loss: 2.3055 - reshape_4_loss: 2.4663 - reshape_5_loss: 2.3779 - reshape_1_acc: 0.5898 - reshape_2_acc: 0.5675 - reshape_3_acc: 0.5799 - reshape_4_acc: 0.5849 - reshape_5_acc: 0.5700 - val_loss: 3.5862 - val_reshape_1_loss: 0.7328 - val_reshape_2_loss: 0.7266 - val_reshape_3_loss: 0.7066 - val_reshape_4_loss: 0.7103 - val_reshape_5_loss: 0.7100 - val_reshape_1_acc: 0.4752 - val_reshape_2_acc: 0.4505 - val_reshape_3_acc: 0.5198 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4653
Epoch 157/500
 - 2s - loss: 11.2610 - reshape_1_loss: 2.1329 - reshape_2_loss: 2.0770 - reshape_3_loss: 2.3380 - reshape_4_loss: 2.3648 - reshape_5_loss: 2.3483 - reshape_1_acc: 0.5787 - reshape_2_acc: 0.5799 - reshape_3_acc: 0.5762 - reshape_4_acc: 0.5539 - reshape_5_acc: 0.5713 - val_loss: 3.5696 - val_reshape_1_loss: 0.7379 - val_reshape_2_loss: 0.7183 - val_reshape_3_loss: 0.6972 - val_reshape_4_loss: 0.7014

Epoch 169/500
 - 2s - loss: 11.4942 - reshape_1_loss: 2.1686 - reshape_2_loss: 2.3386 - reshape_3_loss: 2.2639 - reshape_4_loss: 2.4441 - reshape_5_loss: 2.2790 - reshape_1_acc: 0.5898 - reshape_2_acc: 0.5638 - reshape_3_acc: 0.5948 - reshape_4_acc: 0.5737 - reshape_5_acc: 0.5948 - val_loss: 3.5836 - val_reshape_1_loss: 0.7451 - val_reshape_2_loss: 0.7125 - val_reshape_3_loss: 0.6851 - val_reshape_4_loss: 0.6995 - val_reshape_5_loss: 0.7415 - val_reshape_1_acc: 0.4752 - val_reshape_2_acc: 0.4802 - val_reshape_3_acc: 0.5347 - val_reshape_4_acc: 0.5347 - val_reshape_5_acc: 0.4653
Epoch 170/500
 - 2s - loss: 11.1087 - reshape_1_loss: 2.1506 - reshape_2_loss: 2.1246 - reshape_3_loss: 2.2435 - reshape_4_loss: 2.1501 - reshape_5_loss: 2.4398 - reshape_1_acc: 0.5985 - reshape_2_acc: 0.5725 - reshape_3_acc: 0.5985 - reshape_4_acc: 0.5836 - reshape_5_acc: 0.5589 - val_loss: 3.5664 - val_reshape_1_loss: 0.7405 - val_reshape_2_loss: 0.7043 - val_reshape_3_loss: 0.6972 - val_reshape_4_loss: 0.7051

Epoch 182/500
 - 2s - loss: 11.6097 - reshape_1_loss: 2.1133 - reshape_2_loss: 2.3165 - reshape_3_loss: 2.3611 - reshape_4_loss: 2.4863 - reshape_5_loss: 2.3327 - reshape_1_acc: 0.5539 - reshape_2_acc: 0.5489 - reshape_3_acc: 0.5452 - reshape_4_acc: 0.5341 - reshape_5_acc: 0.5143 - val_loss: 3.5314 - val_reshape_1_loss: 0.7146 - val_reshape_2_loss: 0.7053 - val_reshape_3_loss: 0.6956 - val_reshape_4_loss: 0.6957 - val_reshape_5_loss: 0.7203 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4010 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5050 - val_reshape_5_acc: 0.4158
Epoch 183/500
 - 2s - loss: 12.0783 - reshape_1_loss: 2.2404 - reshape_2_loss: 2.2975 - reshape_3_loss: 2.6162 - reshape_4_loss: 2.5557 - reshape_5_loss: 2.3684 - reshape_1_acc: 0.5304 - reshape_2_acc: 0.5291 - reshape_3_acc: 0.5105 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5093 - val_loss: 3.5282 - val_reshape_1_loss: 0.7100 - val_reshape_2_loss: 0.7083 - val_reshape_3_loss: 0.6958 - val_reshape_4_loss: 0.6946

Epoch 195/500
 - 2s - loss: 11.5748 - reshape_1_loss: 2.3328 - reshape_2_loss: 2.1021 - reshape_3_loss: 2.5436 - reshape_4_loss: 2.3832 - reshape_5_loss: 2.2130 - reshape_1_acc: 0.5328 - reshape_2_acc: 0.5700 - reshape_3_acc: 0.5489 - reshape_4_acc: 0.5452 - reshape_5_acc: 0.5366 - val_loss: 3.5357 - val_reshape_1_loss: 0.7179 - val_reshape_2_loss: 0.7124 - val_reshape_3_loss: 0.6980 - val_reshape_4_loss: 0.6954 - val_reshape_5_loss: 0.7120 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4802 - val_reshape_4_acc: 0.5050 - val_reshape_5_acc: 0.4356
Epoch 196/500
 - 2s - loss: 12.0122 - reshape_1_loss: 2.4485 - reshape_2_loss: 2.4025 - reshape_3_loss: 2.4895 - reshape_4_loss: 2.4190 - reshape_5_loss: 2.2527 - reshape_1_acc: 0.5452 - reshape_2_acc: 0.5564 - reshape_3_acc: 0.5266 - reshape_4_acc: 0.5465 - reshape_5_acc: 0.5415 - val_loss: 3.5339 - val_reshape_1_loss: 0.7182 - val_reshape_2_loss: 0.7118 - val_reshape_3_loss: 0.6975 - val_reshape_4_loss: 0.6948

Epoch 208/500
 - 2s - loss: 11.7337 - reshape_1_loss: 2.2669 - reshape_2_loss: 2.1675 - reshape_3_loss: 2.2962 - reshape_4_loss: 2.5296 - reshape_5_loss: 2.4734 - reshape_1_acc: 0.5341 - reshape_2_acc: 0.5539 - reshape_3_acc: 0.5638 - reshape_4_acc: 0.5465 - reshape_5_acc: 0.5304 - val_loss: 3.5397 - val_reshape_1_loss: 0.7192 - val_reshape_2_loss: 0.7130 - val_reshape_3_loss: 0.7015 - val_reshape_4_loss: 0.6933 - val_reshape_5_loss: 0.7127 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4901 - val_reshape_4_acc: 0.4901 - val_reshape_5_acc: 0.4455
Epoch 209/500
 - 2s - loss: 11.9407 - reshape_1_loss: 2.4394 - reshape_2_loss: 2.1890 - reshape_3_loss: 2.3521 - reshape_4_loss: 2.5612 - reshape_5_loss: 2.3991 - reshape_1_acc: 0.5415 - reshape_2_acc: 0.5254 - reshape_3_acc: 0.5489 - reshape_4_acc: 0.5514 - reshape_5_acc: 0.5316 - val_loss: 3.5674 - val_reshape_1_loss: 0.7337 - val_reshape_2_loss: 0.7177 - val_reshape_3_loss: 0.7033 - val_reshape_4_loss: 0.6951

Epoch 221/500
 - 2s - loss: 12.1286 - reshape_1_loss: 2.5831 - reshape_2_loss: 2.0143 - reshape_3_loss: 2.5719 - reshape_4_loss: 2.5642 - reshape_5_loss: 2.3951 - reshape_1_acc: 0.5093 - reshape_2_acc: 0.5613 - reshape_3_acc: 0.5316 - reshape_4_acc: 0.5229 - reshape_5_acc: 0.5378 - val_loss: 3.5536 - val_reshape_1_loss: 0.7310 - val_reshape_2_loss: 0.7139 - val_reshape_3_loss: 0.7003 - val_reshape_4_loss: 0.6953 - val_reshape_5_loss: 0.7131 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4752 - val_reshape_4_acc: 0.5099 - val_reshape_5_acc: 0.4455
Epoch 222/500
 - 2s - loss: 12.0681 - reshape_1_loss: 2.3971 - reshape_2_loss: 2.2081 - reshape_3_loss: 2.1724 - reshape_4_loss: 2.4955 - reshape_5_loss: 2.7951 - reshape_1_acc: 0.5229 - reshape_2_acc: 0.5489 - reshape_3_acc: 0.5477 - reshape_4_acc: 0.5378 - reshape_5_acc: 0.4944 - val_loss: 3.5430 - val_reshape_1_loss: 0.7198 - val_reshape_2_loss: 0.7132 - val_reshape_3_loss: 0.7053 - val_reshape_4_loss: 0.6935

Epoch 234/500
 - 2s - loss: 11.5012 - reshape_1_loss: 2.1407 - reshape_2_loss: 2.3790 - reshape_3_loss: 2.2881 - reshape_4_loss: 2.2443 - reshape_5_loss: 2.4491 - reshape_1_acc: 0.5613 - reshape_2_acc: 0.5440 - reshape_3_acc: 0.5527 - reshape_4_acc: 0.5626 - reshape_5_acc: 0.5056 - val_loss: 3.5412 - val_reshape_1_loss: 0.7237 - val_reshape_2_loss: 0.7114 - val_reshape_3_loss: 0.7071 - val_reshape_4_loss: 0.6924 - val_reshape_5_loss: 0.7066 - val_reshape_1_acc: 0.3960 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.4455
Epoch 235/500
 - 2s - loss: 12.2183 - reshape_1_loss: 2.4586 - reshape_2_loss: 2.2619 - reshape_3_loss: 2.5331 - reshape_4_loss: 2.3799 - reshape_5_loss: 2.5849 - reshape_1_acc: 0.5415 - reshape_2_acc: 0.5502 - reshape_3_acc: 0.5316 - reshape_4_acc: 0.5452 - reshape_5_acc: 0.5155 - val_loss: 3.5644 - val_reshape_1_loss: 0.7357 - val_reshape_2_loss: 0.7150 - val_reshape_3_loss: 0.6996 - val_reshape_4_loss: 0.6933

Epoch 247/500
 - 2s - loss: 12.8167 - reshape_1_loss: 2.5115 - reshape_2_loss: 2.6143 - reshape_3_loss: 2.5885 - reshape_4_loss: 2.6308 - reshape_5_loss: 2.4717 - reshape_1_acc: 0.5452 - reshape_2_acc: 0.5291 - reshape_3_acc: 0.5415 - reshape_4_acc: 0.5328 - reshape_5_acc: 0.5167 - val_loss: 3.5783 - val_reshape_1_loss: 0.7366 - val_reshape_2_loss: 0.7233 - val_reshape_3_loss: 0.7041 - val_reshape_4_loss: 0.6962 - val_reshape_5_loss: 0.7182 - val_reshape_1_acc: 0.3960 - val_reshape_2_acc: 0.4109 - val_reshape_3_acc: 0.4802 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.4455
Epoch 248/500
 - 2s - loss: 11.3521 - reshape_1_loss: 2.1460 - reshape_2_loss: 2.6047 - reshape_3_loss: 2.2791 - reshape_4_loss: 2.1120 - reshape_5_loss: 2.2103 - reshape_1_acc: 0.5527 - reshape_2_acc: 0.5452 - reshape_3_acc: 0.5576 - reshape_4_acc: 0.5514 - reshape_5_acc: 0.5304 - val_loss: 3.5270 - val_reshape_1_loss: 0.7202 - val_reshape_2_loss: 0.7092 - val_reshape_3_loss: 0.7010 - val_reshape_4_loss: 0.6909

Epoch 260/500
 - 2s - loss: 11.9144 - reshape_1_loss: 2.6324 - reshape_2_loss: 2.3094 - reshape_3_loss: 2.6052 - reshape_4_loss: 2.2218 - reshape_5_loss: 2.1456 - reshape_1_acc: 0.5403 - reshape_2_acc: 0.5452 - reshape_3_acc: 0.5316 - reshape_4_acc: 0.5824 - reshape_5_acc: 0.5539 - val_loss: 3.5238 - val_reshape_1_loss: 0.7266 - val_reshape_2_loss: 0.7020 - val_reshape_3_loss: 0.7007 - val_reshape_4_loss: 0.6890 - val_reshape_5_loss: 0.7055 - val_reshape_1_acc: 0.4356 - val_reshape_2_acc: 0.4901 - val_reshape_3_acc: 0.5149 - val_reshape_4_acc: 0.5446 - val_reshape_5_acc: 0.4703
Epoch 261/500
 - 2s - loss: 12.0612 - reshape_1_loss: 2.3328 - reshape_2_loss: 2.2624 - reshape_3_loss: 2.3528 - reshape_4_loss: 2.6154 - reshape_5_loss: 2.4978 - reshape_1_acc: 0.5452 - reshape_2_acc: 0.5428 - reshape_3_acc: 0.5465 - reshape_4_acc: 0.5266 - reshape_5_acc: 0.4969 - val_loss: 3.5642 - val_reshape_1_loss: 0.7386 - val_reshape_2_loss: 0.7078 - val_reshape_3_loss: 0.7041 - val_reshape_4_loss: 0.6978

Epoch 273/500
 - 2s - loss: 11.4016 - reshape_1_loss: 2.2490 - reshape_2_loss: 2.4583 - reshape_3_loss: 2.1289 - reshape_4_loss: 2.3335 - reshape_5_loss: 2.2319 - reshape_1_acc: 0.5601 - reshape_2_acc: 0.5279 - reshape_3_acc: 0.5440 - reshape_4_acc: 0.5700 - reshape_5_acc: 0.5700 - val_loss: 3.5385 - val_reshape_1_loss: 0.7228 - val_reshape_2_loss: 0.7002 - val_reshape_3_loss: 0.7038 - val_reshape_4_loss: 0.6966 - val_reshape_5_loss: 0.7152 - val_reshape_1_acc: 0.4307 - val_reshape_2_acc: 0.4604 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.4356
Epoch 274/500
 - 2s - loss: 12.1282 - reshape_1_loss: 2.2960 - reshape_2_loss: 2.5328 - reshape_3_loss: 2.5460 - reshape_4_loss: 2.2206 - reshape_5_loss: 2.5328 - reshape_1_acc: 0.5626 - reshape_2_acc: 0.5390 - reshape_3_acc: 0.5576 - reshape_4_acc: 0.5638 - reshape_5_acc: 0.5304 - val_loss: 3.5418 - val_reshape_1_loss: 0.7230 - val_reshape_2_loss: 0.7070 - val_reshape_3_loss: 0.7010 - val_reshape_4_loss: 0.7012

Epoch 286/500
 - 2s - loss: 11.8770 - reshape_1_loss: 2.2736 - reshape_2_loss: 2.4470 - reshape_3_loss: 2.2860 - reshape_4_loss: 2.3639 - reshape_5_loss: 2.5064 - reshape_1_acc: 0.5353 - reshape_2_acc: 0.5489 - reshape_3_acc: 0.5700 - reshape_4_acc: 0.5539 - reshape_5_acc: 0.5415 - val_loss: 3.5626 - val_reshape_1_loss: 0.7426 - val_reshape_2_loss: 0.7188 - val_reshape_3_loss: 0.6962 - val_reshape_4_loss: 0.6914 - val_reshape_5_loss: 0.7136 - val_reshape_1_acc: 0.4307 - val_reshape_2_acc: 0.4950 - val_reshape_3_acc: 0.5000 - val_reshape_4_acc: 0.5545 - val_reshape_5_acc: 0.4604
Epoch 287/500
 - 2s - loss: 12.2627 - reshape_1_loss: 2.6386 - reshape_2_loss: 2.5034 - reshape_3_loss: 2.5499 - reshape_4_loss: 2.3897 - reshape_5_loss: 2.1812 - reshape_1_acc: 0.5465 - reshape_2_acc: 0.5403 - reshape_3_acc: 0.5428 - reshape_4_acc: 0.5688 - reshape_5_acc: 0.5440 - val_loss: 3.5581 - val_reshape_1_loss: 0.7395 - val_reshape_2_loss: 0.7141 - val_reshape_3_loss: 0.6972 - val_reshape_4_loss: 0.6908

Epoch 299/500
 - 2s - loss: 11.6927 - reshape_1_loss: 2.2243 - reshape_2_loss: 2.4929 - reshape_3_loss: 2.2333 - reshape_4_loss: 2.3249 - reshape_5_loss: 2.4172 - reshape_1_acc: 0.5812 - reshape_2_acc: 0.5514 - reshape_3_acc: 0.5613 - reshape_4_acc: 0.5601 - reshape_5_acc: 0.5353 - val_loss: 3.5373 - val_reshape_1_loss: 0.7207 - val_reshape_2_loss: 0.7062 - val_reshape_3_loss: 0.7088 - val_reshape_4_loss: 0.7029 - val_reshape_5_loss: 0.6987 - val_reshape_1_acc: 0.4455 - val_reshape_2_acc: 0.4802 - val_reshape_3_acc: 0.4703 - val_reshape_4_acc: 0.5248 - val_reshape_5_acc: 0.4752
Epoch 300/500
 - 2s - loss: 11.7699 - reshape_1_loss: 2.3451 - reshape_2_loss: 2.2497 - reshape_3_loss: 2.2770 - reshape_4_loss: 2.2499 - reshape_5_loss: 2.6483 - reshape_1_acc: 0.5638 - reshape_2_acc: 0.5626 - reshape_3_acc: 0.5812 - reshape_4_acc: 0.5936 - reshape_5_acc: 0.5353 - val_loss: 3.5815 - val_reshape_1_loss: 0.7411 - val_reshape_2_loss: 0.7190 - val_reshape_3_loss: 0.7025 - val_reshape_4_loss: 0.7152

Epoch 312/500
 - 2s - loss: 11.4251 - reshape_1_loss: 2.4149 - reshape_2_loss: 2.3303 - reshape_3_loss: 2.3252 - reshape_4_loss: 2.1708 - reshape_5_loss: 2.1840 - reshape_1_acc: 0.5366 - reshape_2_acc: 0.5378 - reshape_3_acc: 0.5564 - reshape_4_acc: 0.5812 - reshape_5_acc: 0.5601 - val_loss: 3.5488 - val_reshape_1_loss: 0.7283 - val_reshape_2_loss: 0.7056 - val_reshape_3_loss: 0.6850 - val_reshape_4_loss: 0.7015 - val_reshape_5_loss: 0.7284 - val_reshape_1_acc: 0.4505 - val_reshape_2_acc: 0.5000 - val_reshape_3_acc: 0.5396 - val_reshape_4_acc: 0.5297 - val_reshape_5_acc: 0.4455
Epoch 313/500
 - 2s - loss: 11.7387 - reshape_1_loss: 2.3242 - reshape_2_loss: 2.3997 - reshape_3_loss: 2.3375 - reshape_4_loss: 2.4888 - reshape_5_loss: 2.1885 - reshape_1_acc: 0.5675 - reshape_2_acc: 0.5601 - reshape_3_acc: 0.5886 - reshape_4_acc: 0.5700 - reshape_5_acc: 0.5700 - val_loss: 3.5900 - val_reshape_1_loss: 0.7358 - val_reshape_2_loss: 0.7199 - val_reshape_3_loss: 0.7011 - val_reshape_4_loss: 0.7004

Epoch 325/500
 - 2s - loss: 10.9001 - reshape_1_loss: 2.2911 - reshape_2_loss: 1.9831 - reshape_3_loss: 2.2065 - reshape_4_loss: 2.1904 - reshape_5_loss: 2.2290 - reshape_1_acc: 0.5923 - reshape_2_acc: 0.5898 - reshape_3_acc: 0.5886 - reshape_4_acc: 0.6283 - reshape_5_acc: 0.5576 - val_loss: 3.6339 - val_reshape_1_loss: 0.7567 - val_reshape_2_loss: 0.7222 - val_reshape_3_loss: 0.7064 - val_reshape_4_loss: 0.7329 - val_reshape_5_loss: 0.7157 - val_reshape_1_acc: 0.4356 - val_reshape_2_acc: 0.4406 - val_reshape_3_acc: 0.5050 - val_reshape_4_acc: 0.5050 - val_reshape_5_acc: 0.4208
Epoch 326/500
 - 2s - loss: 11.3825 - reshape_1_loss: 2.2211 - reshape_2_loss: 2.0611 - reshape_3_loss: 2.4129 - reshape_4_loss: 2.3526 - reshape_5_loss: 2.3349 - reshape_1_acc: 0.5564 - reshape_2_acc: 0.5713 - reshape_3_acc: 0.5626 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5328 - val_loss: 3.5309 - val_reshape_1_loss: 0.7295 - val_reshape_2_loss: 0.7069 - val_reshape_3_loss: 0.6840 - val_reshape_4_loss: 0.7008

Epoch 338/500
 - 2s - loss: 11.6912 - reshape_1_loss: 2.2515 - reshape_2_loss: 2.5081 - reshape_3_loss: 2.6152 - reshape_4_loss: 2.2094 - reshape_5_loss: 2.1071 - reshape_1_acc: 0.5378 - reshape_2_acc: 0.5378 - reshape_3_acc: 0.5291 - reshape_4_acc: 0.5638 - reshape_5_acc: 0.5378 - val_loss: 3.5246 - val_reshape_1_loss: 0.7117 - val_reshape_2_loss: 0.7099 - val_reshape_3_loss: 0.6958 - val_reshape_4_loss: 0.6943 - val_reshape_5_loss: 0.7129 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 339/500
 - 2s - loss: 12.0612 - reshape_1_loss: 2.3098 - reshape_2_loss: 2.2911 - reshape_3_loss: 2.6144 - reshape_4_loss: 2.5593 - reshape_5_loss: 2.2867 - reshape_1_acc: 0.5366 - reshape_2_acc: 0.5390 - reshape_3_acc: 0.5328 - reshape_4_acc: 0.5341 - reshape_5_acc: 0.5353 - val_loss: 3.5263 - val_reshape_1_loss: 0.7130 - val_reshape_2_loss: 0.7103 - val_reshape_3_loss: 0.6962 - val_reshape_4_loss: 0.6948

Epoch 351/500
 - 2s - loss: 12.0622 - reshape_1_loss: 2.1920 - reshape_2_loss: 2.4526 - reshape_3_loss: 2.2264 - reshape_4_loss: 2.7460 - reshape_5_loss: 2.4452 - reshape_1_acc: 0.5452 - reshape_2_acc: 0.5440 - reshape_3_acc: 0.5576 - reshape_4_acc: 0.5279 - reshape_5_acc: 0.5217 - val_loss: 3.5463 - val_reshape_1_loss: 0.7231 - val_reshape_2_loss: 0.7137 - val_reshape_3_loss: 0.6958 - val_reshape_4_loss: 0.6958 - val_reshape_5_loss: 0.7178 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 352/500
 - 2s - loss: 11.6523 - reshape_1_loss: 2.1776 - reshape_2_loss: 2.2801 - reshape_3_loss: 2.3421 - reshape_4_loss: 2.3323 - reshape_5_loss: 2.5202 - reshape_1_acc: 0.5390 - reshape_2_acc: 0.5527 - reshape_3_acc: 0.5502 - reshape_4_acc: 0.5626 - reshape_5_acc: 0.5204 - val_loss: 3.5403 - val_reshape_1_loss: 0.7188 - val_reshape_2_loss: 0.7121 - val_reshape_3_loss: 0.6957 - val_reshape_4_loss: 0.6957

Epoch 364/500
 - 2s - loss: 11.5837 - reshape_1_loss: 2.1987 - reshape_2_loss: 2.2114 - reshape_3_loss: 2.5091 - reshape_4_loss: 2.4973 - reshape_5_loss: 2.1672 - reshape_1_acc: 0.5527 - reshape_2_acc: 0.5502 - reshape_3_acc: 0.5465 - reshape_4_acc: 0.5403 - reshape_5_acc: 0.5477 - val_loss: 3.5489 - val_reshape_1_loss: 0.7275 - val_reshape_2_loss: 0.7116 - val_reshape_3_loss: 0.6951 - val_reshape_4_loss: 0.6955 - val_reshape_5_loss: 0.7191 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.5000 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 365/500
 - 2s - loss: 12.0128 - reshape_1_loss: 2.6560 - reshape_2_loss: 2.5347 - reshape_3_loss: 2.1609 - reshape_4_loss: 2.2954 - reshape_5_loss: 2.3658 - reshape_1_acc: 0.5130 - reshape_2_acc: 0.5316 - reshape_3_acc: 0.5477 - reshape_4_acc: 0.5415 - reshape_5_acc: 0.5279 - val_loss: 3.5381 - val_reshape_1_loss: 0.7186 - val_reshape_2_loss: 0.7115 - val_reshape_3_loss: 0.6950 - val_reshape_4_loss: 0.6946

Epoch 377/500
 - 2s - loss: 10.9183 - reshape_1_loss: 2.0210 - reshape_2_loss: 2.3549 - reshape_3_loss: 2.4118 - reshape_4_loss: 2.0304 - reshape_5_loss: 2.1002 - reshape_1_acc: 0.5489 - reshape_2_acc: 0.5502 - reshape_3_acc: 0.5217 - reshape_4_acc: 0.5750 - reshape_5_acc: 0.5341 - val_loss: 3.5323 - val_reshape_1_loss: 0.7099 - val_reshape_2_loss: 0.7136 - val_reshape_3_loss: 0.6960 - val_reshape_4_loss: 0.6938 - val_reshape_5_loss: 0.7188 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.5000 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 378/500
 - 2s - loss: 11.8121 - reshape_1_loss: 2.4005 - reshape_2_loss: 2.4748 - reshape_3_loss: 2.2988 - reshape_4_loss: 2.3765 - reshape_5_loss: 2.2614 - reshape_1_acc: 0.5366 - reshape_2_acc: 0.5403 - reshape_3_acc: 0.5551 - reshape_4_acc: 0.5304 - reshape_5_acc: 0.5341 - val_loss: 3.5529 - val_reshape_1_loss: 0.7193 - val_reshape_2_loss: 0.7191 - val_reshape_3_loss: 0.6978 - val_reshape_4_loss: 0.6963

Epoch 390/500
 - 2s - loss: 11.9772 - reshape_1_loss: 2.5543 - reshape_2_loss: 2.4239 - reshape_3_loss: 2.2744 - reshape_4_loss: 2.5144 - reshape_5_loss: 2.2103 - reshape_1_acc: 0.5180 - reshape_2_acc: 0.5378 - reshape_3_acc: 0.5366 - reshape_4_acc: 0.5403 - reshape_5_acc: 0.5452 - val_loss: 3.5565 - val_reshape_1_loss: 0.7276 - val_reshape_2_loss: 0.7156 - val_reshape_3_loss: 0.6977 - val_reshape_4_loss: 0.6941 - val_reshape_5_loss: 0.7215 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4158
Epoch 391/500
 - 2s - loss: 12.3684 - reshape_1_loss: 2.3523 - reshape_2_loss: 2.4819 - reshape_3_loss: 2.6195 - reshape_4_loss: 2.5928 - reshape_5_loss: 2.3219 - reshape_1_acc: 0.5279 - reshape_2_acc: 0.5341 - reshape_3_acc: 0.5204 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5316 - val_loss: 3.5548 - val_reshape_1_loss: 0.7220 - val_reshape_2_loss: 0.7141 - val_reshape_3_loss: 0.6997 - val_reshape_4_loss: 0.6932

Epoch 403/500
 - 2s - loss: 12.1727 - reshape_1_loss: 2.4798 - reshape_2_loss: 2.4692 - reshape_3_loss: 2.3991 - reshape_4_loss: 2.7242 - reshape_5_loss: 2.1003 - reshape_1_acc: 0.5366 - reshape_2_acc: 0.5477 - reshape_3_acc: 0.5428 - reshape_4_acc: 0.5155 - reshape_5_acc: 0.5489 - val_loss: 3.5681 - val_reshape_1_loss: 0.7340 - val_reshape_2_loss: 0.7191 - val_reshape_3_loss: 0.7034 - val_reshape_4_loss: 0.6941 - val_reshape_5_loss: 0.7174 - val_reshape_1_acc: 0.4059 - val_reshape_2_acc: 0.4307 - val_reshape_3_acc: 0.4950 - val_reshape_4_acc: 0.4950 - val_reshape_5_acc: 0.4356
Epoch 404/500
 - 2s - loss: 11.6534 - reshape_1_loss: 2.4034 - reshape_2_loss: 2.2843 - reshape_3_loss: 2.6543 - reshape_4_loss: 2.3682 - reshape_5_loss: 1.9431 - reshape_1_acc: 0.5428 - reshape_2_acc: 0.5353 - reshape_3_acc: 0.5266 - reshape_4_acc: 0.5390 - reshape_5_acc: 0.5613 - val_loss: 3.5534 - val_reshape_1_loss: 0.7216 - val_reshape_2_loss: 0.7177 - val_reshape_3_loss: 0.6990 - val_reshape_4_loss: 0.7008

Epoch 416/500
 - 2s - loss: 11.4041 - reshape_1_loss: 2.1444 - reshape_2_loss: 2.3176 - reshape_3_loss: 2.4042 - reshape_4_loss: 2.2832 - reshape_5_loss: 2.2547 - reshape_1_acc: 0.5663 - reshape_2_acc: 0.5502 - reshape_3_acc: 0.5353 - reshape_4_acc: 0.5477 - reshape_5_acc: 0.5539 - val_loss: 3.5298 - val_reshape_1_loss: 0.7266 - val_reshape_2_loss: 0.7079 - val_reshape_3_loss: 0.6949 - val_reshape_4_loss: 0.6940 - val_reshape_5_loss: 0.7065 - val_reshape_1_acc: 0.4455 - val_reshape_2_acc: 0.4752 - val_reshape_3_acc: 0.5347 - val_reshape_4_acc: 0.5198 - val_reshape_5_acc: 0.4455
Epoch 417/500
 - 2s - loss: 12.1519 - reshape_1_loss: 2.3789 - reshape_2_loss: 2.4057 - reshape_3_loss: 2.5477 - reshape_4_loss: 2.3848 - reshape_5_loss: 2.4348 - reshape_1_acc: 0.5514 - reshape_2_acc: 0.5452 - reshape_3_acc: 0.5390 - reshape_4_acc: 0.5489 - reshape_5_acc: 0.5328 - val_loss: 3.5396 - val_reshape_1_loss: 0.7230 - val_reshape_2_loss: 0.7118 - val_reshape_3_loss: 0.7065 - val_reshape_4_loss: 0.6909

Epoch 429/500
 - 2s - loss: 11.5250 - reshape_1_loss: 2.4113 - reshape_2_loss: 2.4352 - reshape_3_loss: 2.2217 - reshape_4_loss: 2.3033 - reshape_5_loss: 2.1535 - reshape_1_acc: 0.5366 - reshape_2_acc: 0.5415 - reshape_3_acc: 0.5713 - reshape_4_acc: 0.5675 - reshape_5_acc: 0.5403 - val_loss: 3.5578 - val_reshape_1_loss: 0.7281 - val_reshape_2_loss: 0.7142 - val_reshape_3_loss: 0.7053 - val_reshape_4_loss: 0.7032 - val_reshape_5_loss: 0.7070 - val_reshape_1_acc: 0.4554 - val_reshape_2_acc: 0.4554 - val_reshape_3_acc: 0.5198 - val_reshape_4_acc: 0.5050 - val_reshape_5_acc: 0.4455
Epoch 430/500
 - 2s - loss: 11.3661 - reshape_1_loss: 2.3956 - reshape_2_loss: 2.2082 - reshape_3_loss: 2.3871 - reshape_4_loss: 2.4289 - reshape_5_loss: 1.9462 - reshape_1_acc: 0.5428 - reshape_2_acc: 0.5489 - reshape_3_acc: 0.5489 - reshape_4_acc: 0.5601 - reshape_5_acc: 0.5737 - val_loss: 3.5487 - val_reshape_1_loss: 0.7299 - val_reshape_2_loss: 0.7169 - val_reshape_3_loss: 0.6975 - val_reshape_4_loss: 0.7003

Epoch 442/500
 - 2s - loss: 11.0457 - reshape_1_loss: 2.1771 - reshape_2_loss: 2.5097 - reshape_3_loss: 2.3763 - reshape_4_loss: 2.0225 - reshape_5_loss: 1.9600 - reshape_1_acc: 0.5675 - reshape_2_acc: 0.5204 - reshape_3_acc: 0.5477 - reshape_4_acc: 0.5824 - reshape_5_acc: 0.5514 - val_loss: 3.5431 - val_reshape_1_loss: 0.7239 - val_reshape_2_loss: 0.7148 - val_reshape_3_loss: 0.6950 - val_reshape_4_loss: 0.6921 - val_reshape_5_loss: 0.7172 - val_reshape_1_acc: 0.4356 - val_reshape_2_acc: 0.4554 - val_reshape_3_acc: 0.5248 - val_reshape_4_acc: 0.5495 - val_reshape_5_acc: 0.4505
Epoch 443/500
 - 2s - loss: 11.7988 - reshape_1_loss: 2.1100 - reshape_2_loss: 2.5181 - reshape_3_loss: 2.3834 - reshape_4_loss: 2.3180 - reshape_5_loss: 2.4694 - reshape_1_acc: 0.5564 - reshape_2_acc: 0.5217 - reshape_3_acc: 0.5514 - reshape_4_acc: 0.5477 - reshape_5_acc: 0.5316 - val_loss: 3.5478 - val_reshape_1_loss: 0.7276 - val_reshape_2_loss: 0.7133 - val_reshape_3_loss: 0.6995 - val_reshape_4_loss: 0.6945

Epoch 455/500
 - 2s - loss: 12.1976 - reshape_1_loss: 2.4418 - reshape_2_loss: 2.7286 - reshape_3_loss: 2.3957 - reshape_4_loss: 2.4789 - reshape_5_loss: 2.1526 - reshape_1_acc: 0.5390 - reshape_2_acc: 0.5204 - reshape_3_acc: 0.5465 - reshape_4_acc: 0.5428 - reshape_5_acc: 0.5316 - val_loss: 3.5650 - val_reshape_1_loss: 0.7287 - val_reshape_2_loss: 0.7181 - val_reshape_3_loss: 0.6930 - val_reshape_4_loss: 0.7058 - val_reshape_5_loss: 0.7193 - val_reshape_1_acc: 0.4505 - val_reshape_2_acc: 0.4604 - val_reshape_3_acc: 0.5198 - val_reshape_4_acc: 0.5099 - val_reshape_5_acc: 0.4604
Epoch 456/500
 - 2s - loss: 11.1616 - reshape_1_loss: 2.1476 - reshape_2_loss: 2.0536 - reshape_3_loss: 2.2072 - reshape_4_loss: 2.4799 - reshape_5_loss: 2.2732 - reshape_1_acc: 0.5428 - reshape_2_acc: 0.5551 - reshape_3_acc: 0.5638 - reshape_4_acc: 0.5489 - reshape_5_acc: 0.5514 - val_loss: 3.5335 - val_reshape_1_loss: 0.7150 - val_reshape_2_loss: 0.7095 - val_reshape_3_loss: 0.6986 - val_reshape_4_loss: 0.7024

Epoch 468/500
 - 2s - loss: 12.0294 - reshape_1_loss: 2.2882 - reshape_2_loss: 2.5671 - reshape_3_loss: 2.0985 - reshape_4_loss: 2.6650 - reshape_5_loss: 2.4105 - reshape_1_acc: 0.5849 - reshape_2_acc: 0.5304 - reshape_3_acc: 0.5713 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5118 - val_loss: 3.5478 - val_reshape_1_loss: 0.7331 - val_reshape_2_loss: 0.7163 - val_reshape_3_loss: 0.6979 - val_reshape_4_loss: 0.6936 - val_reshape_5_loss: 0.7069 - val_reshape_1_acc: 0.4208 - val_reshape_2_acc: 0.4703 - val_reshape_3_acc: 0.5248 - val_reshape_4_acc: 0.5297 - val_reshape_5_acc: 0.4703
Epoch 469/500
 - 2s - loss: 11.4074 - reshape_1_loss: 2.4163 - reshape_2_loss: 2.0735 - reshape_3_loss: 2.1990 - reshape_4_loss: 2.4804 - reshape_5_loss: 2.2381 - reshape_1_acc: 0.5465 - reshape_2_acc: 0.5886 - reshape_3_acc: 0.5589 - reshape_4_acc: 0.5328 - reshape_5_acc: 0.5378 - val_loss: 3.5510 - val_reshape_1_loss: 0.7341 - val_reshape_2_loss: 0.7206 - val_reshape_3_loss: 0.6931 - val_reshape_4_loss: 0.6888

Epoch 481/500
 - 2s - loss: 12.1513 - reshape_1_loss: 2.5602 - reshape_2_loss: 2.4008 - reshape_3_loss: 2.1705 - reshape_4_loss: 2.6410 - reshape_5_loss: 2.3788 - reshape_1_acc: 0.5527 - reshape_2_acc: 0.5638 - reshape_3_acc: 0.5713 - reshape_4_acc: 0.5366 - reshape_5_acc: 0.5279 - val_loss: 3.5901 - val_reshape_1_loss: 0.7416 - val_reshape_2_loss: 0.7274 - val_reshape_3_loss: 0.6996 - val_reshape_4_loss: 0.7098 - val_reshape_5_loss: 0.7118 - val_reshape_1_acc: 0.4455 - val_reshape_2_acc: 0.4653 - val_reshape_3_acc: 0.5396 - val_reshape_4_acc: 0.5050 - val_reshape_5_acc: 0.4802
Epoch 482/500
 - 2s - loss: 11.7321 - reshape_1_loss: 2.2995 - reshape_2_loss: 2.2809 - reshape_3_loss: 2.5844 - reshape_4_loss: 2.3795 - reshape_5_loss: 2.1877 - reshape_1_acc: 0.5688 - reshape_2_acc: 0.5452 - reshape_3_acc: 0.5366 - reshape_4_acc: 0.5663 - reshape_5_acc: 0.5489 - val_loss: 3.5999 - val_reshape_1_loss: 0.7470 - val_reshape_2_loss: 0.7177 - val_reshape_3_loss: 0.7063 - val_reshape_4_loss: 0.7042

Epoch 494/500
 - 2s - loss: 11.6937 - reshape_1_loss: 2.3781 - reshape_2_loss: 2.2347 - reshape_3_loss: 2.1995 - reshape_4_loss: 2.4331 - reshape_5_loss: 2.4483 - reshape_1_acc: 0.5204 - reshape_2_acc: 0.5378 - reshape_3_acc: 0.5279 - reshape_4_acc: 0.5390 - reshape_5_acc: 0.5217 - val_loss: 3.6029 - val_reshape_1_loss: 0.7428 - val_reshape_2_loss: 0.7246 - val_reshape_3_loss: 0.7021 - val_reshape_4_loss: 0.7031 - val_reshape_5_loss: 0.7304 - val_reshape_1_acc: 0.3861 - val_reshape_2_acc: 0.4059 - val_reshape_3_acc: 0.5000 - val_reshape_4_acc: 0.5000 - val_reshape_5_acc: 0.4208
Epoch 495/500
 - 2s - loss: 11.7355 - reshape_1_loss: 2.3286 - reshape_2_loss: 2.0953 - reshape_3_loss: 2.3353 - reshape_4_loss: 2.5010 - reshape_5_loss: 2.4754 - reshape_1_acc: 0.5328 - reshape_2_acc: 0.5564 - reshape_3_acc: 0.5328 - reshape_4_acc: 0.5378 - reshape_5_acc: 0.5105 - val_loss: 3.5693 - val_reshape_1_loss: 0.7254 - val_reshape_2_loss: 0.7186 - val_reshape_3_loss: 0.6988 - val_reshape_4_loss: 0.7007

In [28]:
Y_ = [Y_test[:,i,:] for i in range(5)]

model.evaluate(X_test,Y_)

253/253 [==============================] - 0s 743us/step


[3.5470177062415322,
 0.7131842403072614,
 0.703208977290293,
 0.7089205589219044,
 0.7065947854471772,
 0.7151091525205981,
 0.4545454560767992,
 0.4664031627621104,
 0.42687747188707587,
 0.42687747012013977,
 0.4229249030705026]

In [0]:
model.save('LSTM_20_5_D_180506.save') 

In [30]:
from sklearn.model_selection import train_test_split 

#K_binary = keras.utils.to_categorical(K_label,2)
x = data['training_X']
y = data['training_y'][:,:,1]
y = y[:,:,np.newaxis]
print (x.shape)
print (y.shape)


x_train, x_test, y_train,y_test = train_test_split (x,y, test_size=0.2,shuffle=True)

#Y_train =  Y_train[:,:,np.newaxis]
#Y_test =  Y_test[:,:,np.newaxis]
#Y_train = np.array(Y_train)
print (X_train.shape)
print (Y_train.shape)
print (Y_train[:10])

(1262, 20, 5)
(1262, 5, 1)
(1009, 20, 5)
(1009, 5, 1)
[[[0.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [0.]
  [1.]
  [1.]
  [0.]]

 [[0.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[0.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[0.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [0.]
  [0.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[0.]
  [0.]
  [1.]
  [0.]
  [1.]]

 [[1.]
  [0.]
  [1.]
  [1.]
  [1.]]]


In [31]:
y_ = [y_test[:,i,:] for i in range (5)]
model.evaluate(x_test,y_)

253/253 [==============================] - 0s 810us/step


[3.504758054559881,
 0.7060149783202311,
 0.6975688194568921,
 0.6991454984830774,
 0.6995540694756941,
 0.7024746841121569,
 0.4308300392901002,
 0.48221343849958637,
 0.48616600943648297,
 0.47035573146088794,
 0.4782608693296259]